### PR TITLE
code review

### PR DESCRIPTION
**Pull request by frederic-mahe**
hi @Locutus73, here are some suggestions.

There are parts of the code I don't understand. Could you please add comments to clarify your intent? Thanks.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
More specifically, reading `update.sh` I am not sure to understand what this code is doing:
```sh
if [ -f $INI_PATH ]
then
	eval "$(cat $INI_PATH | tr -d '\r')"
fi
```

**Comment by Locutus73** [comment]
Sorry, I was very busy this week and I couldn't answer.
The whole idea of this section of code
```
ORIGINAL_SCRIPT_PATH="$0"
if [ "$ORIGINAL_SCRIPT_PATH" == "bash" ]
then
	ORIGINAL_SCRIPT_PATH=$(ps | grep "^ *$PPID " | grep -o "[^ ]*$")
fi
INI_PATH=${ORIGINAL_SCRIPT_PATH%.*}.ini
if [ -f $INI_PATH ]
then
	eval "$(cat $INI_PATH | tr -d '\r')"
fi
```
* getting the script name
* since mister_updater.sh can be called by update.sh through a `curl ... | bash -` and $0 results being "bash", when needed I get the original calling script name through `$(ps | grep "^ *$PPID " | grep -o "[^ ]*$")` ($PPID is automatically initialized with process ID in MiSTer Linux)
* replacing the script extension with "ini"
* including this "ini" file (which actually isn't an INI, it's a bash scritpt) in current script

This way you can make an "ini" file which redefines the user settings variables. If the users calls directly mister_updater.sh, mister_update.ini will be included. If the user uses update.sh which loads mister_updater.sh from GitHub, both will include update.ini. If the user wants a specific update_arcade.sh he can just copy/rename update.sh and make an update_arcade.ini. The `tr -d '\r'` is for Windows users which usually make text files with CrLf.

I tried to explain this process in the README.md.

**Comment by frederic-mahe** [comment]
Indeed, it was explained in the README. My bad. Thanks for the explanations though, this is much clearer to me now.

Based on your explanations, I've prepared another batch of patches.

**Comment by frederic-mahe** [comment]
> Is [ deprecated? I see [[ has more features, but is it 100% syntactically backward compatible? Is it available on all modern shells?

`[[` is not POSIX, but it is one of the most portable and consistent non-POSIX extensions available. I've never used a system were it was not available. And since that script is aiming for busybox and systems equipped with modern shells in general, I think it is advantageous to use it.

> I get the readability point, but really can a # with no space confuse shell interpretation?

Well, this is unlikely. But one example is `#!`, and there are also job schedulers on computer clusters that rely on lines starting with `#command`. Best practice is to put a space after `#`.

> Can you briefly explain the use ${} for delineating variable names? Is it more elegant? Does it help variable parsing?

It is mostly useful when grouping variables and text: `${var1}${var2}` or `${var1}.txt`. With `${}` there is no ambiguity on the variable you are calling. If you have var="myfile" and var1="otherfile", what file will this command create? `touch $var1.txt`

> Does dos2unix actually alter the "ini" file? I guess so and it would confuse a windows user editing the ini again using notepad... he would see just one long line and get mad. So I prefer the catless previous solution...

You are right. I have a new commit to correct that.

Thanks for your patience. I've received my DE-10 nano a couple days ago and your installation script does an awesome job! I cannot imagine how long it would take to manually install all the cores and configuration files...

**Comment by frederic-mahe** [comment]
@Locutus73 with the latest edits, everything seems to work as intended on my MiSTer (I did not thoroughly tested user-variable loading through the ".ini" file though).

I'd be honored if you could accept my commits.

**Comment by Locutus73** [comment]
> I'd be honored if you could accept my commits.

I'll merge your commits for sure... sorry if I may seem rude not accepting them in the last week but I was very busy (and lazy :) ). I will merge as soon as I can try your edited script and I will apply what you taught to me to mister_updater.sh too.
Thank you.

**Comment by frederic-mahe** [comment]
> Hi Frederic. Have this any benefit over the original `ps | grep "^ *$PPID " | grep -o "[^ ]*$"`, I mean apart the `${}` ?

The patch I suggest uses `ps`'s options to eliminate unwanted data (user, time, command arguments). We end up with only two columns to parse. `Awk` allows to capture a line if and only if the PID column contains **exactly** the value `${PPID}` and then returns only the content of the command column. Maybe that's semantically closer to the original intent of the code? It is also potentially more robust to changes in `ps`'s behavior.

```sh
ps -o comm,pid | awk -v PPID=${PPID} '$2 == PPID {print $1}'
```

`Awk` can parse tables where columns are separated by variable numbers of blank characters. This is more robust than relying on `grep` and  regular expressions to parse an output formatted for human-readability, like `ps`'s output.

Also, that's one less pipe, so one less subshell to spawn, and a (slightly) faster execution time :-)

**Comment by frederic-mahe** [comment]
> sorry if I may seem rude not accepting them in the last week but I was very busy

No problem at all. I am busy too, I know how it is :-)

**Comment by frederic-mahe** [comment]
I've tested this script in my MiSTer tonight, and everything seems to work as expected, including loading an ".ini" file.

**Comment by Locutus73** [comment]
Thank you so much for the marvelous work Frédéric.

**Pull request merged**
