### PR TITLE
Handle HTML character codes for square brackets and ampersand

### PR DESCRIPTION
**Pull request by tjanas**
Creates a file named something like:
`Arkanoid (Unl. lives) [hb].mra`
instead of
`Arkanoid (Unl. lives) %5Bhb%5D.mra`

or
`Pac & Pal.mra`
instead of
`Pac %26 Pal.mra`

### CODE REVIEW

**Comment by tjanas** [comment]
I tested this with my branch and it seemed to work fine:

Successfully updated cores:
Arkanoid (Unl. Lives, slower) [hb].mra, Arkanoid (Unl. lives) [hb].mra, Moon Cresta (Galaxian Hardware) [bl].mra, Omega [bl].mra, Super Glob (Pac-Man, German) [bl].mra, Mighty Monkey (Scramble Hardware) [bl].mra, Space Race [TTL].mra, Pac & Pal.mra, Pac-Man & Chomp Chomp.mra, V'Ball (US) [bl].mra, Zig Zag (Dig Dug Conversion) [bl].mra

**Comment by tjanas** [comment]
I've found some @jotego cores have multiple spaces in the MRA filename (e.g. `Quiz & Dragons  Capcom Quiz Game -USA 920701-.mra`, two spaces between Dragons and Capcom).

Adding the following to the sed may condense multiple consecutive spaces to a single space in the filename:
`s/   */ /g`

**Comment by jotego** [comment]
I think these changes are needed. The only problem we face is that the updater doesn't delete old MRA files AFAIK.

**Comment by atrac17** [comment]
I've been trying to think of a way to delete old MRA files. But at least this will make life easier. Unfortunately, I just redid all my patch offset's to remove brackets. @tjanas the plan is to update all of CPS-1 and MRA's that used an old format so everything is uniform. It's the removing old MRA files for users that is the biggest pain. Ah, my old friend `sed`.

**Comment by tjanas** [comment]
Will do more testing and may reopen later.

**Comment by mario-64** [comment]
Once this gets merged, how best should we handle our existing MRA's to avoid duplicates?  Can you just delete them all and the updater will re-download?

**Comment by tjanas** [comment]
> Once this gets merged, how best should we handle our existing MRA's to avoid duplicates? Can you just delete them all and the updater will re-download?

Yes. And delete the following before re-running update.sh:
`/media/fat/Scripts/.mister_updater/update.last_successful_run` 
`/media/fat/Scripts/.mister_updater/MRA-Alternatives_20210223.zip`

**Comment by tjanas** [comment]
@Locutus73 could you review and squash & merge if it looks good?

**Comment by tjanas** [comment]
It has been merged in the jotego fork: https://github.com/jotego/Updater_script_MiSTer/pull/2

**Comment by mario-64** [comment]
> > Once this gets merged, how best should we handle our existing MRA's to avoid duplicates? Can you just delete them all and the updater will re-download?
> 
> Yes. And delete the following before re-running update.sh:
> `/media/fat/Scripts/.mister_updater/update.last_successful_run`
> `/media/fat/Scripts/.mister_updater/MRA-Alternatives_20210223.zip`

I just did this and ran update_all. I'm still seeing some of the garbage characters in my games list. Am I too soon? Is this change available yet?

**Comment by atrac17** [comment]
Not merged. It is on jtupdater.

**Pull request merged**
